import type { BlogPost } from "@/types";

/**
 * Posts that ship inside the bundle so the published blog renders content
 * without any DynamoDB write. These are merged into the PUBLISHED read path
 * only (see `getAllPosts` / `getPostBySlug` in `lib/blog-db.ts`); the admin
 * path never sees them, and a real DB post always wins on a slug collision.
 */
export const SEED_POSTS: BlogPost[] = [
  {
    id: "seed-evaluating-rag-faithfulness-ragas",
    slug: "evaluating-rag-faithfulness-ragas",
    title: "What RAGAS taught me about evaluating RAG faithfulness",
    excerpt:
      "Building a RAG pipeline for UK financial regulation was the interesting part. Knowing whether its answers were actually grounded - not just fluent - is what RAGAS forced me to measure.",
    type: "blog",
    tags: ["RAG", "RAGAS", "Neo4j", "Sentence Transformers"],
    published: true,
    createdAt: "2026-07-01T08:15:00.000Z",
    updatedAt: "2026-07-01T08:15:00.000Z",
    content: [
      "FinLaw-UK was my MSc dissertation: a retrieval-augmented generation pipeline for UK financial regulation. The corpus is genuinely hard. The FCA Handbook alone runs to thousands of pages, cross-referenced with MiFID II, the PRA Rulebook, and a stack of binding technical standards. A naive LLM lookup answers confidently and wrongly in exactly the places where being wrong is most expensive.",
      "",
      "Building the retrieval and generation was the interesting engineering. The harder question came afterwards: how do I know an answer is actually grounded in the source, and not just fluent? That question is where RAGAS earned its place in the project.",
      "",
      "## Fluent and correct are not the same thing",
      "",
      "The first thing to accept is that surface metrics do not work here.",
      "",
      "BLEU and ROUGE reward text that reads like the reference. For regulatory text, that is close to worthless - a fluent paraphrase with one wrong citation is a liability, and it scores just as well as a correct answer. What I needed to measure was different: does the answer stay grounded in the context that was actually retrieved, and does it address the question that was actually asked? RAGAS scores exactly those two things, faithfulness and answer relevance, and both need an LLM judge reading the answer against the retrieved context rather than against a golden string.",
      "",
      "> A polished answer and a hallucinated one look identical until you check them against the source.",
      "",
      "## What faithfulness actually checks",
      "",
      "Faithfulness asks whether every claim in the answer is supported by the retrieved context. The idea is easier to see as a sketch than to describe:",
      "",
      "```python",
      "# Illustrative sketch of the idea - RAGAS uses an LLM judge, not this code",
      "claims = extract_claims(answer)",
      "supported = [c for c in claims if entailed_by(c, retrieved_context)]",
      "faithfulness = len(supported) / max(len(claims), 1)",
      "```",
      "",
      "A score near 1.0 means the answer invented nothing; a lower score means part of it came from the model's parameters rather than the documents in front of it. That framing quietly moves the burden onto retrieval - the generator can only be as faithful as the context it is handed.",
      "",
      "## The retrieval has to earn the score",
      "",
      "This is where plain vector search falls down. Dense retrieval finds passages that are semantically similar, but it misses the structure: a single rule is only meaningful alongside its parent chapter, the entities it obligates, and the rules it cross-references. Similarity does not recover that. The regulatory graph does.",
      "",
      "So ingestion runs two streams in parallel. Each section is chunked to its smallest semantic unit - usually a single rule - then embedded with Sentence Transformers into a vector index and, separately, parsed into a Neo4j knowledge graph that captures Rule-to-Chapter, Rule-to-Entity, and Rule-to-Cross-reference relationships.",
      "",
      "Generation itself is the easy part to describe: it runs locally on Mistral 7B-Instruct under citation-required prompting, where every claim has to reference a chunk ID and every chunk ID it cites has to exist in the retrieved set. That constraint is what makes a faithfulness score meaningful rather than aspirational. The interesting work happens before it, at query time:",
      "",
      "- Dense retrieval pulls the top-K candidate chunks.",
      "- A single-hop Cypher expansion in Neo4j adds adjacent rules, parent-chapter context, and cross-referenced sections.",
      "- The expanded set is re-ranked and trimmed to fit Mistral 7B-Instruct's context window.",
      "",
      "## The decisions that shaped it",
      "",
      "A few of them I would defend again:",
      "",
      "- Graph expansion over a better reranker - the failure mode was missing context, not mis-ranked context, and no reranker recovers a passage that was never retrieved.",
      "- Neo4j over a vector-only store like Pinecone or Qdrant - the cross-reference graph is the actual moat, and one Cypher hop expands it cheaply.",
      "- Mistral 7B over a frontier API - a small open-weight model running locally proved the retrieval gains held regardless of generator size, with no vendor dependency or data-egress problem on sensitive text.",
      "",
      "## What the numbers said, and what they didn't",
      "",
      "On a 110-item benchmark spanning seven regulatory domains, the pipeline reached 0.76 faithfulness and 0.74 answer relevance, with legal completeness at 0.68. Two other figures were in this paragraph until I re-measured the evaluation after submitting it: source accuracy and citation quality both came from a scorer that checked whether a string looked like a citation, not whether it was the right one. Both are withdrawn, and the correction is in the repo.",
      "",
      "The honest reading of 0.76 is that roughly three in four answers stay grounded and about a quarter drift. Those are not numbers to admire; they are the prompt-engineering targets for the next iteration. Answer relevance at 0.74 tracks faithfulness closely, which suggests the model stays on topic when it stays grounded - the two failure modes look related, not independent.",
      "",
      "## Where RAGAS stops helping",
      "",
      "RAGAS is good at catching faithfulness drift. It is not good at catching legal-specific failure modes. An answer can be perfectly grounded in a retrieved passage and still misapply it across jurisdictions, and faithfulness will score that highly. If I were taking this past the dissertation, the next moves are to extend the evaluation harness into a structured legal-reasoning benchmark, and to ship a confidence-aware interface that surfaces uncertainty when the graph expansion returns thin adjacency - so the person reading the answer knows whether it was reasoned from rich context or from sparse.",
    ].join("\n"),
  },
  {
    id: "seed-profiling-async-io-voice-agent-latency",
    slug: "profiling-async-io-voice-agent-latency",
    title: "Profiling async I/O: how we cut voice-agent latency 54%",
    excerpt:
      "A voice agent's quality is dominated by latency, and ours was clearing 2.4 seconds a turn. Getting it down to 1.1s was a profiling problem, not an architecture one.",
    type: "blog",
    tags: ["Python", "FastAPI", "AsyncIO", "PostgreSQL"],
    published: true,
    createdAt: "2026-06-16T09:30:00.000Z",
    updatedAt: "2026-06-16T09:30:00.000Z",
    content: [
      "A voice agent lives or dies on latency. At 2.4 seconds a turn it feels like a bad cell connection and the person on the other end starts talking over it; under 1.2 seconds it feels human enough that they stay on the call. Our outbound agent at Outlyst was clearing 2.4s on warm calls and getting worse under load - past roughly 200 concurrent sessions, response times spiked unpredictably and a fraction of calls dropped outright.",
      "",
      "The instinct in that situation is to reach for a bigger architecture. It was the wrong instinct.",
      "",
      "## The latency is in the middle, not the edges",
      "",
      "Retell AI handles the speech side - recognition and text-to-speech. Our backend only answers structured tool calls in between. So the round-trip a caller actually feels is dominated by what we do in those middle few hundred milliseconds, not by the model or the audio. The problem was not the design; it was measurement - find where the milliseconds go and stop losing them. The target was an average under 1.2s, held stable past 2,000 concurrent sessions, and no horizontal scaling, because throwing machines at it would have quietly killed the unit economics.",
      "",
      "## Profile the process that is actually under load",
      "",
      "I reached for py-spy rather than cProfile, and the reason matters. py-spy samples the running process from the outside, so I could attach it to the production backend under real traffic without restarting anything or distorting the numbers. cProfile's instrumentation would have moved exactly the timings I was trying to read.",
      "",
      "> A profiler that changes the timing it measures is measuring the wrong program.",
      "",
      "```bash",
      "# Illustrative: sample the live backend and render a flame graph",
      "py-spy record --pid $(pgrep -f 'uvicorn') --duration 60 --output profile.svg",
      "```",
      "",
      "The flame graph and the asyncio task traces surfaced two bottlenecks the request-rate dashboards had never shown:",
      "",
      "- A synchronous ORM call on every tool invocation, blocking the event loop.",
      "- A connection pool sized for the wrong shape of load - tuned for short HTTP request bursts, not long-lived websocket sessions.",
      "",
      "## Get the blocking call off the event loop",
      "",
      "One synchronous database call on the hot path does not just slow that one request - it stalls every coroutine sharing the loop. So I moved the hot path off SQLAlchemy and onto asyncpg.",
      "",
      "That was a deliberate trade. SQLAlchemy's async support is real, but its abstraction layers show up in a flame graph as frames you cannot cut. asyncpg is the actual driver: no ORM, no relationship modelling, no migrations at request time - none of which the inference backend needs. What it needs is fast reads and writes against a schema it already knows.",
      "",
      "## Size the pool for sessions, not requests",
      "",
      "The pool problem was subtler. A websocket call holds its session open for minutes, not milliseconds. A pool sized for HTTP request volume gave us a few dozen connections trying to serve thousands of concurrent, long-lived sessions, so callers queued on connection acquisition and the latency surfaced everywhere at once. Sizing the pool against the observed in-flight session distribution, rather than peak request rate, removed the contention without adding a single machine.",
      "",
      "## Stop doing independent work in sequence",
      "",
      "A single user turn often needed data from several places at once - CRM, calendar, contact enrichment. Those calls were independent but running one after another, so the turn paid for the sum of them. `asyncio.gather()` collapses them into one await:",
      "",
      "```python",
      "# Illustrative: independent tool calls in one turn, run concurrently",
      "crm, calendar, contact = await asyncio.gather(",
      "    fetch_crm(caller_id),",
      "    fetch_calendar(caller_id),",
      "    enrich_contact(caller_id),",
      ")",
      "```",
      "",
      "Now the turn is as slow as its slowest call, not the sum of all of them.",
      "",
      "There was one more change that was less about speed than waste: a lightweight gatekeeper-detection classifier that runs before the main inference loop. Cheap-and-fast beats expensive-and-smart - there is no reason to spend LLM tokens on a receptionist who is only going to transfer the call. Detected gatekeepers route to a callback scheduler instead of dead-ending, and each gated call saves roughly three to five minutes of call time.",
      "",
      "## What it added up to",
      "",
      "Mean call latency dropped from 2.4s to 1.1s - a 54% reduction - with no horizontal scaling and no change to the model. Across the contract the agent handled 2,100+ outbound calls at that latency. None of it came from a rewrite: the whole win was two profiling findings and a scheduling change.",
      "",
      "## Where the next milliseconds live",
      "",
      "The plumbing is mostly drained now. The next 200ms will not come from the surrounding I/O; it will have to come from the inference itself - speculative decoding, smaller models fine-tuned to the specific tool-call patterns we see, or moving the gatekeeper classifier onto a co-located CPU model so it costs almost nothing to run. That is a different kind of work, and it is where I would point next.",
    ].join("\n"),
  },
  {
    id: "seed-designing-legal-rag-benchmark",
    slug: "designing-legal-rag-benchmark",
    title: "Gold answers and required citations: designing a benchmark for legal RAG",
    excerpt:
      "The FinLaw-UK pipeline was scored against a benchmark I had to build first. Writing 110 legal QA items taught me more about RAG failure modes than building the pipeline did.",
    type: "case-study",
    tags: ["RAG", "Evaluation", "Benchmarks", "Neo4j"],
    published: true,
    createdAt: "2026-08-03T09:00:00.000Z",
    updatedAt: "2026-08-03T09:00:00.000Z",
    content: [
      "Every RAG write-up leads with the pipeline: the embedding model, the graph, the reranker. Almost none of them lead with the thing that decides whether any of it worked - the benchmark. For FinLaw-UK, my MSc dissertation on UK financial regulation QA, nobody hands you an eval set. I had to write one, and building it taught me more about where retrieval systems fail than building the retrieval did.",
      "",
      "## What one benchmark item has to carry",
      "",
      "A useful legal QA item is more than a question and an answer. Each item in the FinLaw-UK set carries four things: the question, a gold answer, the citations a correct answer must include, and the keywords the grader checks for. Here is a real one from the curated tier:",
      "",
      "- Question: \"Which FCA principle introduces the Consumer Duty?\"",
      "- Gold answer: the Consumer Duty is Principle 12, requiring firms to act to deliver good outcomes for retail customers.",
      "- Required citation: PRIN 12.",
      "- Graded keywords: Consumer Duty, good outcomes, Principle 12.",
      "",
      "The required-citation field is the one that earns its keep. The pipeline validates citations against a Neo4j knowledge graph of the regulatory corpus, so an answer citing a rule that does not exist in the graph is flagged as a potential hallucination. The benchmark mirrors that: an answer without PRIN 12 in it is wrong even if the prose is right, because in regulatory work an uncited claim is not an answer - it is a liability.",
      "",
      "## Composition matters more than size",
      "",
      "The full set is 110 items, and the split matters more than the count: 80 short-form questions, 20 document-level tasks, and 10 case-like scenarios, spanning domains from FSMA authorisation and conduct-of-business rules to payment services and complaints handling.",
      "",
      "Each tier probes a different failure mode. Short-form questions check retrieval precision: can the system find the one rule that answers a pointed question? Document tasks check synthesis: can it hold a whole chapter in view without dropping the cross-references? Scenarios check application: given a fact pattern, does it reach for the right regime at all? A benchmark that is all short-form questions will happily certify a system that falls over the moment a question spans two documents.",
      "",
      "## The aggregate score hid a broken scorer",
      "",
      "The headline numbers looked healthy: 0.82 source accuracy, 0.81 citation quality, 0.76 RAGAS faithfulness, 0.74 answer relevance. I submitted on those. Then I went back to reproduce them and found that two of the four were not measuring anything.",
      "",
      "The source-accuracy and citation-quality scorers were regex shape-checks. They tested whether a model output contained something shaped like a citation, not whether that citation was the right one, or real. Anything citation-shaped scored a flat 0.85. Once I looked at the distribution instead of the mean, 103 of the 110 rows carried that identical constant. The true rate, when every citation is resolved against the graph, was 3 in 110.",
      "",
      "> A mean can look reasonable while the distribution underneath it is a single repeated number. Plot the spread before you quote the average.",
      "",
      "Both figures are withdrawn. The repo now ships a measurement-integrity report saying which numbers reproduce and which do not, because a benchmark you release without that is worth less than no benchmark at all. The correction is also what motivated the parts of the system I am proudest of: the citation normaliser, the cross-encoder re-ranker, and the refusal gate that returns nothing rather than a citation it cannot verify.",
      "",
      "Refusing costs something, and the benchmark is what let me price it. Headline answer relevancy drops 23 points, because RAGAS scores a refusal as zero by construction. Exclude the 30 refusals and the mean is 0.658, against 0.641 for the non-refusing baseline. The baseline only scored higher by confabulating answers to questions the corpus cannot support, which is precisely the behaviour the gate exists to stop.",
      "",
      "## Where it actually failed",
      "",
      "The per-domain breakdown told a different story in one corner: consumer redress. DISP - the complaints-handling sourcebook - dragged legal completeness below 0.65. The reason is structural. DISP rules are fragmented into many small, heavily cross-referenced fragments, and the two-hop graph expansion that stitches context back together for the rest of the Handbook could not reassemble them. Rule-level chunking is the right default for most of the corpus; for DISP it shreds the very context the expansion is supposed to recover.",
      "",
      "That is a finding I only have because the benchmark was built to expose it: domain labels on every item meant the failure had an address, not just a lower average.",
      "",
      "## What I would build next",
      "",
      "Two things. Domain-aware chunk granularity for fragmented sourcebooks like DISP, so completeness recovers where the structure is hostile and deeper expansion alone will not do it. And a structured legal-reasoning benchmark beyond RAGAS, because faithfulness scoring cannot catch an answer that is perfectly grounded in a retrieved passage and still misapplies it across jurisdictions. The eval set is public in the repo alongside the pipeline and the integrity report; if you are building anything similar, steal the format - question, gold answer, required citations, graded keywords. The fourth column is the one you will thank yourself for, and it is the one that catches a scorer measuring shape instead of substance.",
    ].join("\n"),
  },
  {
    id: "seed-benchmarking-11-classifiers-diabetes-risk",
    slug: "benchmarking-11-classifiers-diabetes-risk",
    title: "11 classifiers, 253,680 records: what actually moved diabetes-risk accuracy",
    excerpt:
      "The model zoo was the easy part. The choices that moved accuracy were about class balance and what a person can self-report - not the estimator.",
    type: "blog",
    tags: ["Machine Learning", "scikit-learn", "Class Imbalance", "Interpretability"],
    published: true,
    createdAt: "2026-07-20T10:00:00.000Z",
    updatedAt: "2026-07-20T10:00:00.000Z",
    content: [
      "My BSc thesis at COMSATS asked a plain question: from a public health questionnaire, how well can you predict diabetes risk? The dataset was BRFSS 2015 - 253,680 CDC health records, 22 features - and the first thing it taught me was that the obvious way to answer is the wrong one. On an 86/14 imbalance, accuracy is not the question. Sensitivity and ROC-AUC are, because the expensive mistake here is the miss.",
      "",
      "## The imbalance decides before the model does",
      "",
      "BRFSS 2015 is 86/14 imbalanced: non-diabetic records outnumber diabetic ones six to one. That means a model that predicts \"not diabetic\" for everyone scores 86% accuracy while being clinically useless. Any accuracy figure on this dataset is meaningless until the balance is handled.",
      "",
      "We ran three balancing strategies head-to-head - Random Over-Sampling, SMOTE, and ADASYN, with the resampling confined to the training folds so the held-out split stayed untouched:",
      "",
      "```python",
      "# Illustrative: the head-to-head that decided the balancing strategy",
      "for sampler in (RandomOverSampler(), SMOTE(), ADASYN()):",
      "    X_bal, y_bal = sampler.fit_resample(X_train, y_train)",
      "    score = evaluate(model, X_bal, y_bal, X_test, y_test)",
      "```",
      "",
      "Plain Random Over-Sampling won, and the reason is worth remembering: SMOTE and ADASYN interpolate synthetic samples, which blurs categorical questionnaire features. There is no meaningful point halfway between \"has high blood pressure\" and \"does not\". Duplication preserved the feature distributions; interpolation smeared them.",
      "",
      "## Eleven models, one honest winner",
      "",
      "The benchmark spanned linear, instance-based, tree, boosting, and neural families - eleven classifiers under the same 80/20 split. The tree ensembles led, then the instance-based models, with the linear baseline last.",
      "",
      "That ordering was a measured finding, not an assumption. Running the full zoo is tedious, and it is also the only way the sentence \"Random Forest was best\" means anything.",
      "",
      "## Accuracy is not the metric that matters",
      "",
      "For a screening tool, the expensive mistake is the miss. Telling a healthy person to get a check-up costs an appointment; telling a diabetic person they are fine costs years of untreated progression. So the model was tuned to catch positives rather than to look tidy on a single headline metric - accepting more false alarms in exchange for missing fewer real cases. For screening, that is the right side of the trade to be on.",
      "",
      "## The constraint that shaped everything: no lab tests",
      "",
      "Every BRFSS feature is self-reportable - blood pressure history, BMI, activity, general health. That constraint became the product: a 19-question screen anyone can complete without a lab visit, served from a Flask API with a React front end, returning a risk classification and a future-risk probability. A model needing an HbA1c value would have been more precise and useless to the people the tool is for.",
      "",
      "## A prediction without a why is a black box",
      "",
      "Clinical adoption research is blunt about this: when clinicians cannot trace a prediction to features they recognise, they reject the tool - even when it outperforms their judgement. The thesis handled this with correlation-driven risk-factor analysis: general health was the strongest correlate at -0.41, then high blood pressure at +0.38, high cholesterol and BMI at +0.29 each, with prevalence climbing sharply from age 50 onward. Those are drivers a clinician already reasons with, which is the point: the explanation has to be in their vocabulary, not the model's.",
      "",
      "## What I would do differently",
      "",
      "Ship per-prediction attribution, not just population-level correlations - a risk score without \"why this score for this person\" is exactly the black box the thesis argued against. And before anything touches a real clinic: calibration and population-shift detection. 93% on one curated dataset does not transfer to a different hospital's intake unchecked, and Platt-scaled probabilities plus a shift detector are the difference between a paper result and a safe tool.",
    ].join("\n"),
  },
];
