import type { BlogPost } from "@/types";

/**
 * Posts that ship inside the bundle so the published blog renders content
 * without any DynamoDB write. These are merged into the PUBLISHED read path
 * only (see `getAllPosts` / `getPostBySlug` in `lib/blog-db.ts`); the admin
 * path never sees them, and a real DB post always wins on a slug collision.
 */
export const SEED_POSTS: BlogPost[] = [
  {
    id: "seed-evaluating-rag-faithfulness-ragas",
    slug: "evaluating-rag-faithfulness-ragas",
    title: "What RAGAS taught me about evaluating RAG faithfulness",
    excerpt:
      "Building a RAG pipeline for UK financial regulation was the interesting part. Knowing whether its answers were actually grounded — not just fluent — is what RAGAS forced me to measure.",
    type: "blog",
    tags: ["RAG", "RAGAS", "Neo4j", "Sentence Transformers"],
    published: true,
    createdAt: "2026-07-01T08:15:00.000Z",
    updatedAt: "2026-07-01T08:15:00.000Z",
    content: [
      "FinLaw-UK was my MSc dissertation: a retrieval-augmented generation pipeline for UK financial regulation. The corpus is genuinely hard. The FCA Handbook alone runs to thousands of pages, cross-referenced with MiFID II, the PRA Rulebook, and a stack of binding technical standards. A naive LLM lookup answers confidently and wrongly in exactly the places where being wrong is most expensive.",
      "",
      "Building the retrieval and generation was the interesting engineering. The harder question came afterwards: how do I know an answer is actually grounded in the source, and not just fluent? That question is where RAGAS earned its place in the project.",
      "",
      "## Fluent and correct are not the same thing",
      "",
      "The first thing to accept is that surface metrics do not work here.",
      "",
      "BLEU and ROUGE reward text that reads like the reference. For regulatory text, that is close to worthless — a fluent paraphrase with one wrong citation is a liability, and it scores just as well as a correct answer. What I needed to measure was different: does the answer stay grounded in the context that was actually retrieved, and does it address the question that was actually asked? RAGAS scores exactly those two things, faithfulness and answer relevance, and both need an LLM judge reading the answer against the retrieved context rather than against a golden string.",
      "",
      "> A polished answer and a hallucinated one look identical until you check them against the source.",
      "",
      "## What faithfulness actually checks",
      "",
      "Faithfulness asks whether every claim in the answer is supported by the retrieved context. The idea is easier to see as a sketch than to describe:",
      "",
      "```python",
      "# Illustrative sketch of the idea — RAGAS uses an LLM judge, not this code",
      "claims = extract_claims(answer)",
      "supported = [c for c in claims if entailed_by(c, retrieved_context)]",
      "faithfulness = len(supported) / max(len(claims), 1)",
      "```",
      "",
      "A score near 1.0 means the answer invented nothing; a lower score means part of it came from the model's parameters rather than the documents in front of it. That framing quietly moves the burden onto retrieval — the generator can only be as faithful as the context it is handed.",
      "",
      "## The retrieval has to earn the score",
      "",
      "This is where plain vector search falls down. Dense retrieval finds passages that are semantically similar, but it misses the structure: a single rule is only meaningful alongside its parent chapter, the entities it obligates, and the rules it cross-references. Similarity does not recover that. The regulatory graph does.",
      "",
      "So ingestion runs two streams in parallel. Each section is chunked to its smallest semantic unit — usually a single rule — then embedded with Sentence Transformers into a vector index and, separately, parsed into a Neo4j knowledge graph that captures Rule-to-Chapter, Rule-to-Entity, and Rule-to-Cross-reference relationships.",
      "",
      "Generation itself is the easy part to describe: it runs locally on Mistral 7B-Instruct under citation-required prompting, where every claim has to reference a chunk ID and every chunk ID it cites has to exist in the retrieved set. That constraint is what makes a faithfulness score meaningful rather than aspirational. The interesting work happens before it, at query time:",
      "",
      "- Dense retrieval pulls the top-K candidate chunks.",
      "- A single-hop Cypher expansion in Neo4j adds adjacent rules, parent-chapter context, and cross-referenced sections.",
      "- The expanded set is re-ranked and trimmed to fit Mistral 7B-Instruct's context window.",
      "",
      "## The decisions that shaped it",
      "",
      "A few of them I would defend again:",
      "",
      "- Graph expansion over a better reranker — the failure mode was missing context, not mis-ranked context, and no reranker recovers a passage that was never retrieved.",
      "- Neo4j over a vector-only store like Pinecone or Qdrant — the cross-reference graph is the actual moat, and one Cypher hop expands it cheaply.",
      "- Mistral 7B over a frontier API — a small open-weight model running locally proved the retrieval gains held regardless of generator size, with no vendor dependency or data-egress problem on sensitive text.",
      "",
      "## What the numbers said, and what they didn't",
      "",
      "On a held-out evaluation set the pipeline reached 0.76 faithfulness and 0.74 answer relevance, with a 19% accuracy gain over a vector-only baseline. That gain came primarily from queries that required understanding regulatory hierarchy — precisely the cases where graph expansion supplies context that dense retrieval alone drops.",
      "",
      "The honest reading of 0.76 is that roughly three in four answers stay grounded and about a quarter drift. Those are not numbers to admire; they are the prompt-engineering targets for the next iteration. Answer relevance at 0.74 tracks faithfulness closely, which suggests the model stays on topic when it stays grounded — the two failure modes look related, not independent.",
      "",
      "## Where RAGAS stops helping",
      "",
      "RAGAS is good at catching faithfulness drift. It is not good at catching legal-specific failure modes. An answer can be perfectly grounded in a retrieved passage and still misapply it across jurisdictions, and faithfulness will score that highly. If I were taking this past the dissertation, the next moves are to replace the soft-vote evaluation harness with a structured legal-reasoning benchmark, and to ship a confidence-aware interface that surfaces uncertainty when the graph expansion returns thin adjacency — so the person reading the answer knows whether it was reasoned from rich context or from sparse.",
    ].join("\n"),
  },
  {
    id: "seed-profiling-async-io-voice-agent-latency",
    slug: "profiling-async-io-voice-agent-latency",
    title: "Profiling async I/O: how we cut voice-agent latency 54%",
    excerpt:
      "A voice agent's quality is dominated by latency, and ours was clearing 2.4 seconds a turn. Getting it down to 1.1s was a profiling problem, not an architecture one.",
    type: "blog",
    tags: ["Python", "FastAPI", "AsyncIO", "PostgreSQL"],
    published: true,
    createdAt: "2026-06-16T09:30:00.000Z",
    updatedAt: "2026-06-16T09:30:00.000Z",
    content: [
      "A voice agent lives or dies on latency. At 2.4 seconds a turn it feels like a bad cell connection and the person on the other end starts talking over it; under 1.2 seconds it feels human enough that they stay on the call. Our outbound agent at Outlyst was clearing 2.4s on warm calls and getting worse under load — past roughly 200 concurrent sessions, response times spiked unpredictably and a fraction of calls dropped outright.",
      "",
      "The instinct in that situation is to reach for a bigger architecture. It was the wrong instinct.",
      "",
      "## The latency is in the middle, not the edges",
      "",
      "Retell AI handles the speech side — recognition and text-to-speech. Our backend only answers structured tool calls in between. So the round-trip a caller actually feels is dominated by what we do in those middle few hundred milliseconds, not by the model or the audio. The problem was not the design; it was measurement — find where the milliseconds go and stop losing them. The target was an average under 1.2s, held stable past 2,000 concurrent sessions, and no horizontal scaling, because throwing machines at it would have quietly killed the unit economics.",
      "",
      "## Profile the process that is actually under load",
      "",
      "I reached for py-spy rather than cProfile, and the reason matters. py-spy samples the running process from the outside, so I could attach it to the production backend under real traffic without restarting anything or distorting the numbers. cProfile's instrumentation would have moved exactly the timings I was trying to read.",
      "",
      "> A profiler that changes the timing it measures is measuring the wrong program.",
      "",
      "```bash",
      "# Illustrative: sample the live backend and render a flame graph",
      "py-spy record --pid $(pgrep -f 'uvicorn') --duration 60 --output profile.svg",
      "```",
      "",
      "The flame graph and the asyncio task traces surfaced two bottlenecks the request-rate dashboards had never shown:",
      "",
      "- A synchronous ORM call on every tool invocation, blocking the event loop.",
      "- A connection pool sized for the wrong shape of load — tuned for short HTTP request bursts, not long-lived websocket sessions.",
      "",
      "## Get the blocking call off the event loop",
      "",
      "One synchronous database call on the hot path does not just slow that one request — it stalls every coroutine sharing the loop. So I moved the hot path off SQLAlchemy and onto asyncpg.",
      "",
      "That was a deliberate trade. SQLAlchemy's async support is real, but its abstraction layers show up in a flame graph as frames you cannot cut. asyncpg is the actual driver: no ORM, no relationship modelling, no migrations at request time — none of which the inference backend needs. What it needs is fast reads and writes against a schema it already knows.",
      "",
      "## Size the pool for sessions, not requests",
      "",
      "The pool problem was subtler. A websocket call holds its session open for minutes, not milliseconds. A pool sized for HTTP request volume gave us a few dozen connections trying to serve thousands of concurrent, long-lived sessions, so callers queued on connection acquisition and the latency surfaced everywhere at once. Sizing the pool against the observed in-flight session distribution, rather than peak request rate, removed the contention without adding a single machine.",
      "",
      "## Stop doing independent work in sequence",
      "",
      "A single user turn often needed data from several places at once — CRM, calendar, contact enrichment. Those calls were independent but running one after another, so the turn paid for the sum of them. `asyncio.gather()` collapses them into one await:",
      "",
      "```python",
      "# Illustrative: independent tool calls in one turn, run concurrently",
      "crm, calendar, contact = await asyncio.gather(",
      "    fetch_crm(caller_id),",
      "    fetch_calendar(caller_id),",
      "    enrich_contact(caller_id),",
      ")",
      "```",
      "",
      "Now the turn is as slow as its slowest call, not the sum of all of them.",
      "",
      "There was one more change that was less about speed than waste: a lightweight gatekeeper-detection classifier that runs before the main inference loop. Cheap-and-fast beats expensive-and-smart — there is no reason to spend LLM tokens on a receptionist who is only going to transfer the call. Detected gatekeepers route to a callback scheduler instead of dead-ending, and each gated call saves roughly three to five minutes of GPU time.",
      "",
      "## What it added up to",
      "",
      "Mean call latency dropped from 2.4s to 1.1s — a 54% reduction — with no horizontal scaling. The system now holds 2,100+ concurrent stateful websocket sessions without dropping any, where it used to degrade past 200. The downstream effects tracked the latency: a 25% lift in lead conversions, 27 qualified leads out of the gatekeeper-aware routing, and 100+ staff hours a week reclaimed once contact sync ran off automated extraction instead of manual entry.",
      "",
      "## Where the next milliseconds live",
      "",
      "The plumbing is mostly drained now. The next 200ms will not come from the surrounding I/O; it will have to come from the inference itself — speculative decoding, smaller models fine-tuned to the specific tool-call patterns we see, or moving the gatekeeper classifier onto a co-located CPU model so it costs almost nothing to run. That is a different kind of work, and it is where I would point next.",
    ].join("\n"),
  },
];
