import type { BlogPost } from "@/types";

/**
 * Posts that ship inside the bundle so the published blog renders content
 * without any DynamoDB write. These are merged into the PUBLISHED read path
 * only (see `getAllPosts` / `getPostBySlug` in `lib/blog-db.ts`); the admin
 * path never sees them, and a real DB post always wins on a slug collision.
 */
export const SEED_POSTS: BlogPost[] = [
  {
    id: "seed-six-boards-to-twenty-ingest-fan-out",
    slug: "six-boards-to-twenty-ingest-fan-out",
    title: "Six boards to twenty, and the ingest never changed shape",
    excerpt:
      "Jobzyl launched searching six job boards and searches twenty today. What that growth actually tested was one interface, one banned failure mode, and a scheduler that thinks in call budgets rather than clocks.",
    type: "case-study",
    tags: ["FastAPI", "PostgreSQL", "AsyncIO", "Aggregation"],
    published: true,
    createdAt: "2026-06-28T09:00:00.000Z",
    updatedAt: "2026-06-28T09:00:00.000Z",
    content: [
      "Jobzyl went live in June searching six job boards. It searches twenty today, plus company careers boards through seven applicant tracking systems. The interesting part of that sentence is not the number. It is that nothing about the ingest changed shape to get there.",
      "",
      "This is the post I would have wanted before starting: what the fan-out looks like, and which four decisions did the load-bearing work.",
      "",
      "## One interface, twenty-three implementations",
      "",
      "Every source sits behind a single `search()` method. A board is a file, not a migration and not a branch in a scheduler. Indeed, Adzuna and Reed are the global core; Careerjet and Jooble are the workhorses; then the government APIs, which are the underrated tier - Bundesagentur fuer Arbeit, France Travail, JobTechDev in Sweden, MyCareersFuture in Singapore, USAJOBS - and then the remote-only boards. Twenty-three providers are implemented, twenty are disclosed publicly.",
      "",
      "The fan-out is parallel with a per-provider timeout, because twenty boards in sequence is a minutes-long wait and one slow board should never be able to hold the response. That part is obvious. The part that was not obvious is the failure mode it creates.",
      "",
      "## A provider that swallows its own errors reports 100% success forever",
      "",
      "The natural way to write a provider is defensively:",
      "",
      "```python",
      "async def search(self, query):",
      "    try:",
      "        return await self._fetch(query)",
      "    except httpx.HTTPError:",
      "        return []          # looks careful. is a lie.",
      "```",
      "",
      "That code never fails. It also never reports, and an aggregator that cannot tell an empty board from a broken one has no idea what it is serving. A board that has been down for a week looks exactly like a board with no matching jobs.",
      "",
      "So swallowing is banned at the base class. A provider that raises is recorded as failed and the response says so; the only thing allowed to return an empty list is a board that genuinely answered with nothing. It is a two-line rule and it is the single most valuable decision in the ingest, because every coverage number downstream depends on it being true.",
      "",
      "> If a provider cannot fail, you are not measuring providers. You are measuring your own optimism.",
      "",
      "## Nine providers do not know what a country is",
      "",
      "Nine of the sources ignore location entirely: they hand you the whole feed and expect you to filter it yourself. That is fine once. The scrape queue works through keyword-by-country pairs, so without a cache those nine refetched byte-identical feeds once per pair. Arbeitnow's feed alone is 1.98 MB.",
      "",
      "The fix is a request-level HTTP cache keyed on url, params and headers, with a TTL and a 256-entry LRU. One deliberate hole in it: failures are not cached. Caching a 503 turns a thirty-second outage into a TTL-long one, and the whole point of the previous section is that a failure has to stay visible.",
      "",
      "## Company careers boards, by guessing",
      "",
      "The seven ATS integrations - Greenhouse, Lever, Ashby, SmartRecruiters, Workable, Recruitee, Teamtailor - read a company's own careers board rather than an aggregator's copy of it. The listings are fresher and the descriptions are intact.",
      "",
      "The catch is that no ATS publishes an index of its customers. There is no endpoint that says which companies are on Greenhouse. So discovery is slug guessing against a name list: 68.6% of 140 company names resolved in 29.8 seconds. Guessing does not scale by itself, so it prunes itself - names go out in bands of 500, and the run stops once three consecutive bands come in under a 15% yield floor. The floor is what keeps a long tail of misses from eating a budget that has better uses.",
      "",
      "## The write path failed in the least interesting way possible",
      "",
      "PostgREST connects with an 8-second statement timeout. One upsert of 10,350 rows hit it, died, and took an entire sweep with it. Rows go through a chunked RPC now, and it chunks on two bounds rather than one: a row count and a byte count. Row count alone is not enough, because job descriptions vary enough in size that 2,000 short rows and 2,000 long ones are not the same request.",
      "",
      "Retention has a similar shape of bug in it. Rows rotate into an archive table at 30 days, on `coalesce(date_posted, created_at)` rather than `date_posted` - about 40% of listings state no date at all, and on the naive column every one of them dodges retention forever. Nothing a user saved is ever archived, whatever its age.",
      "",
      "## Deduplication is part of the write, not a cleanup job",
      "",
      "The same role sits on four boards under four URLs, and the reader wants one row. That needs an identity key that is stable across sources: accent-folded, punctuation-stripped, company legal suffixes dropped. It runs at write time and again on every read path, because a write-time pass can only see one batch and a duplicate that arrives tomorrow is still a duplicate.",
      "",
      "The key is deliberately conservative. It merges nothing it cannot prove, which means it happily leaves duplicates on the table rather than merge two jobs that differ:",
      "",
      "[[embed:dedupe-key]]",
      "",
      "The location row in that demo is the honest limit. The key cannot tell that Clifton is in Bristol, so those stay as two rows. I would rather ship a visible duplicate than silently merge two different jobs, because one of those failures a reader can see and correct for.",
      "",
      "## Scheduling is a budget problem, not a clock problem",
      "",
      "Three schedules run. A 6-hourly scrape. A 30-minute queue tick that claims work under leases from a queue of keyword-by-country pairs, roughly 968 pairs a day, where pairs that keep coming back empty retire themselves. And a weekly breadth sweep that is sized by a call budget rather than by a duration.",
      "",
      "That last one is where I got it wrong first. The sweep is depth-weighted: a country with a real provider locale gets the full keyword library, and a country reachable only through one global board gets about 113 breadth-first keywords instead. Spending deep-first burned a 40,000-call budget on 19 locations and left 90 countries with nothing at all. The thin tier is reserved first now. Breadth is worth more than depth when the alternative is a country that returns zero rows.",
      "",
      "## What going from six to twenty actually tested",
      "",
      "Not throughput. The thing that got tested was whether each new board could be added without a new special case, and the answer was yes fourteen times, which is the only evidence I trust that the interface was drawn in the right place.",
      "",
      "What it did not test is whether the boards are worth having. Five sources account for most of the corpus, and on the last census six of the twenty had contributed no rows at all. A search queries up to twenty boards. It does not draw on twenty evenly, and I would rather write that sentence than the one that sounds better.",
    ].join("\n"),
  },
  {
    id: "seed-ranking-is-the-product-postgres-full-text",
    slug: "ranking-is-the-product-postgres-full-text",
    title: "Ranking is the product: 27.4% of results had nothing to do with the query",
    excerpt:
      "Retrieval stopped being the hard part once the index got big. Ordering took over, and the first version shipped a quarter of its results with none of the query in the job title.",
    type: "case-study",
    tags: ["PostgreSQL", "Full-text Search", "SSE", "Search Relevance"],
    published: true,
    createdAt: "2026-07-27T09:00:00.000Z",
    updatedAt: "2026-07-27T09:00:00.000Z",
    content: [
      "By July the index had stopped being small, and the problem moved. Finding matching listings was no longer hard. Ordering them was, and I had been treating ordering as a detail of the query.",
      "",
      "Then I measured it. In the shape I shipped first, 27.4% of results came back with none of the user's search words anywhere in the job title.",
      "",
      "Not wrong rows exactly. Rows that mentioned the query somewhere in a 4,000-word description while the title said something else entirely. To a reader scanning a list of titles, that is indistinguishable from a broken search.",
      "",
      "## Ranking belongs in the database, not the query builder",
      "",
      "The ordering now lives in a Postgres function. The full-text index weights the title above the description, which is the whole fix, and it comes with a trap worth naming because it cost me an afternoon.",
      "",
      "Those weights are only ever read by `ts_rank_cd`. Set the weights and keep ordering by something else, and nothing happens. Rank with `ts_rank_cd` over an unweighted index, and nothing happens either. The weighting and the ranking function are one change spread across two files, and each half is inert on its own - which is exactly the kind of change that looks applied, passes review, and does nothing.",
      "",
      "One thing that is deliberately absent from that function: sponsorship. There was a paid-placement term in an early version and a migration took it out. A ranking that can be bought is not a ranking, and it is the one thing a job seeker has no way to detect from the outside.",
      "",
      "## Streaming, because the honest wait is not zero",
      "",
      "A live search across twenty boards takes as long as the slowest board you are still willing to wait for. You can hide that behind a spinner or you can show it, so search streams over SSE and reports per-provider progress as each board answers.",
      "",
      "SSE rather than a WebSocket: progress is a one-way push, SSE is a single HTTP request that reconnects on its own, and the upgrade dance buys nothing when nothing travels upstream.",
      "",
      "The cache and the live fan-out are also two different products, and only one of them is free. Anyone can search what the index already holds, with no account. The live fan-out needs one. Two details of that gate turned out to matter more than the gate itself: it sits on the pipeline step rather than on one entry branch, because there are three ways into a search and a check per branch is a check you will forget to add to the fourth. And every result event carries a capability flag, so a frontend deployed ahead of the backend degrades instead of guessing.",
      "",
      "## Paging that does not re-sort the world",
      "",
      "A few cheap decisions, each of which was a bug first:",
      "",
      "- Singleflight on identical concurrent queries. Two people searching the same thing at the same second run it once.",
      "- Keyset paging rather than OFFSET, so page 40 costs what page 2 costs.",
      "- Cross-scrape deduplication from page 2 onward. Page 1 is the one the reader is waiting on, and it is already deduplicated at write time.",
      "- A 60-day age ceiling that does not delete undated rows, because dropping everything with no stated date would silently discard about 40% of the corpus.",
      "",
      "## A count that lies about itself",
      "",
      "There are eleven filter dimensions, and every option carries a count. The subtle part is which rows a count is allowed to see.",
      "",
      "A facet count has to apply every filter except the one it is counting. Otherwise the number beside an unselected option is zero by construction, and zero answers a question nobody asked. What a reader wants to know is what they will be left with if they click, and that is only computable by leaving that dimension out of its own filter:",
      "",
      "[[embed:facet-counts]]",
      "",
      "Flip that toggle with a filter active and the numbers beside every unselected option collapse. That is what the naive version shipped, and it makes a filter panel look broken in a way that is very hard to describe in a bug report.",
      "",
      "## Explaining an empty result set",
      "",
      "Pay is stated on none of the first twenty UK, French or German listings for most roles. So a reader who filters on pay gets nothing back, and an empty list with no explanation reads as a broken product rather than as a fact about job boards.",
      "",
      "There is a blame function for that: when a result set is empty, it works out which filter is responsible and says so. It is a small piece of code and it is the difference between a filter that looks broken and a filter that just told you something true about the market.",
      "",
      "## Two fields search must never pay for",
      "",
      "The detail endpoint is separate from search on purpose. It carries the full description, a pay estimate, and when the liveness sweep last confirmed the URL. Those last two are the reason for the split: computing an estimate and a freshness check for every one of 5,000 search rows is real money for two fields a reader only sees on the one row they opened.",
      "",
      "## What relevance actually is",
      "",
      "Search is a promise about ordering, not about retrieval. Any index can return rows that contain a word. What a reader is trusting is that the first ten are the first ten for a reason they would agree with if you explained it - which is why the ranking lives in one function they could read, with no term in it that anybody paid for.",
    ].join("\n"),
  },
  {
    id: "seed-three-scores-one-cv-semantic-matching",
    slug: "three-scores-one-cv-semantic-matching",
    title: "Three scores, one CV: keyword, semantic, and the one that leaves",
    excerpt:
      "Keyword extraction in the browser, cosine similarity in pgvector, and Claude for the writing. Three paths rather than one, because they differ in what they can see and how far your CV has to travel.",
    type: "case-study",
    tags: ["pgvector", "Embeddings", "Claude", "Privacy"],
    published: true,
    createdAt: "2026-08-12T09:00:00.000Z",
    updatedAt: "2026-08-12T09:00:00.000Z",
    content: [
      "The reason I started Jobzyl was not really the searching. It was the other half: you send a CV, you hear nothing, and you never learn which of the two things went wrong. So the product has to answer a question I find genuinely uncomfortable to answer - does this CV fit this job - and it has to answer it without overclaiming.",
      "",
      "It ended up as three separate scoring paths rather than one. That was not indecision. The three differ in what they can see, what they cost, and how far your CV has to travel, and collapsing them into a single number would have hidden exactly the part that matters.",
      "",
      "[[embed:match-paths]]",
      "",
      "## The keyword path, and the bug that defined the whole feature",
      "",
      "The first path runs in the page. The CV is parsed in the browser, skills are extracted from a local dictionary unioned with the server's own extraction from the full posting, and the percentage is computed next to you. Nothing is uploaded, and no account is needed.",
      "",
      "It shipped with a bug that I now think of as the design brief for everything else. If a posting named no skills at all - and plenty of postings are three paragraphs of culture and a phone number - the score was a confident **0%**.",
      "",
      "Zero. Rendered identically to a genuine mismatch. A reader has no way to tell \"your CV does not fit this job\" from \"this posting did not say what it wants\", and those are opposite facts.",
      "",
      "So the percentage is gated on how many skills the posting actually named. Below the threshold it does not show a number, it says the posting did not name enough to judge. The score got less impressive and much more useful, and that trade is the entire product in one change.",
      "",
      "> A score that cannot say \"I do not know\" is not a score. It is a decoration that happens to be numeric.",
      "",
      "## The semantic path, which is what people mean by matching",
      "",
      "Keyword extraction has a hard ceiling: it only matches vocabulary. A CV saying Postgres and a posting asking for PostgreSQL are the same skill and zero shared tokens. Ten years of this problem is why embeddings exist.",
      "",
      "So a saved CV is embedded once and stored as a vector, and fit is cosine similarity against job embeddings in pgvector. Same index, one extra use: the up-to-24-row similar-jobs list on a posting is the same query run from the job's vector instead of yours.",
      "",
      "Two things I would defend about how narrow this is. It is opt-in, because it structurally requires the CV in the database and I did not want that to be the default that happens to you. And it stays first-party: the vector and the encrypted text sit in Postgres, and the score is computed there. The similarity number is never produced by a third party.",
      "",
      "## The path that leaves",
      "",
      "The third layer is Claude, and it is the only one where your CV leaves the system. It writes cover letters, prepares interview questions, and gives CV feedback - drafted prose, not a score.",
      "",
      "Two engineering notes on it. A job description is untrusted text from a third-party board, and it is about to be concatenated with a system prompt and a CV, so every call wraps the posting in delimited blocks under a system guard. Prompt injection via a job ad is not hypothetical for a product whose entire input is scraped text. And the calls sit under a per-user daily quota, because a generous free tier on a metered API is a bill, not a feature.",
      "",
      "The transfer is to the US under EU standard contractual clauses. That sentence is on the about page and in the privacy policy, and writing it there was a decision: omitting it would have been easy, technically survivable, and the exact thing I would resent as a user.",
      "",
      "## Where the CV physically sits",
      "",
      "The boring layer, which is the one that would actually hurt someone if I got it wrong.",
      "",
      "- CV text is encrypted at rest with Fernet, and the backend refuses to start in production without the key. A missing key should stop a deploy, not quietly store plaintext.",
      "- Multiple CVs per account, and the default flag moves through one atomic RPC rather than two sequential updates. Two updates have a window where either both or neither is default.",
      "- The in-browser copy lives in `sessionStorage`, not `localStorage`. A CV should not outlive the tab on a shared machine.",
      "",
      "## What I am not claiming",
      "",
      "No number here says anything about outcomes. I have no measurement of whether a match score gets anyone more interviews, no testimonial, and no logo wall, because none of those has been earned. The site says so in the one place a reader would look for it.",
      "",
      "What the three paths are for is smaller and, I think, more defensible: telling you where you stand before you spend an evening on an application, and being explicit about which of them needed your CV to leave the browser to do it.",
    ].join("\n"),
  },
  {
    id: "seed-what-a-job-aggregator-is-allowed-to-claim",
    slug: "what-a-job-aggregator-is-allowed-to-claim",
    title: "49 of 50 salaries were not salaries: what a job aggregator is allowed to claim",
    excerpt:
      "Fetching a million job listings is an afternoon. Deciding what you are willing to say about them - the pay, the dedup, whether the role still exists - is the whole engineering problem.",
    type: "case-study",
    tags: ["PostgreSQL", "Data Quality", "FastAPI", "Supabase"],
    published: true,
    createdAt: "2026-08-19T09:00:00.000Z",
    updatedAt: "2026-08-19T09:00:00.000Z",
    content: [
      "Jobzyl searches 20 job boards and thousands of company careers pages in one query, over an index of more than two million live postings. People assume the hard part is the fetching. It is not. Any afternoon gets you a fan-out across twenty APIs.",
      "",
      "The hard part is what you are willing to say about a listing once you have it. An aggregator inherits every gap in every source it reads, and it inherits them silently: the listing that was filled three weeks ago, the salary that is not the employer's number, the figure that is a day rate wearing an annual costume, the same role sitting on four boards under four URLs. Pass all of that through as fact and you have built something worse than the twenty tabs it replaced, because now the twenty tabs have one confident voice.",
      "",
      "So the rule the whole backend enforces is narrow: never state something the data does not support. Here is what that cost.",
      "",
      "## Zero does not mean unpaid",
      "",
      "Start with pay, because pay is where a job seeker's trust actually lives.",
      "",
      "A provider returning `0` for salary means it had nothing. It does not mean the role is unpaid, so zero is dropped rather than rendered. That one is easy. The interesting case is a figure like GBP 450.",
      "",
      "I know GBP 450 is not an annual salary. I do not know what it is. It could be a day rate, an hourly rate on a badly parsed field, or a typo with three zeroes missing. Inferring \"daily\" would look like a fix and would actually be worse than the bug: it replaces a wrong fact with an invented one, and an invented one is much harder to spot later.",
      "",
      "```python",
      "# The gate, in spirit: convert only to check, never to display.",
      "if amount == 0:",
      "    return None              # the provider had nothing",
      "if not plausible_annual(amount, period):",
      "    return None              # wrong, and I cannot tell how",
      "return Pay(amount, period)   # in the period the employer quoted",
      "```",
      "",
      "Pay renders in the period the employer quoted, or it does not render. There is no normalising step that quietly turns an unknown into an annual figure.",
      "",
      "## A model's output is plausible by construction",
      "",
      "Then a measurement I did not expect. Adzuna returns a flag saying when a figure is its own market estimate rather than a number the employer wrote. I checked how often that flag was set: on 2026-08-18, 49 of 50 US data-scientist rows that carried any pay at all were predicted.",
      "",
      "> A plausibility check cannot catch this. The whole point of a good model is that its output looks like the real thing.",
      "",
      "Those figures had been rendering as quotes, under a promise of employer-stated pay. They are now out of aggregation entirely and styled distinctly wherever they still appear. The general lesson is uncomfortable: the values most likely to slip past your validation are the ones generated by something that was optimised to pass it.",
      "",
      "## An estimate that only speaks when the employer did not",
      "",
      "Two thirds of listings state no pay at all, and \"salary not specified\" is a genuinely bad experience. So there is an estimate. It is a lookup over measured cells rather than a model, it never argues with a stated figure, and it has no country-wide fallback, because a national median tells a nurse nothing whatsoever about nursing.",
      "",
      "One detail there took a rewrite. Cells have to be deduplicated per job before anything is counted. A single poster ran the same role 220 times at an identical figure, and on raw row counts that one poster set a UK salary cell on their own. Every UK engineer reading that number would have taken it as the market. A median is only as honest as the assumption that its rows are independent, and job postings are emphatically not.",
      "",
      "## The listing that was already gone",
      "",
      "Until this month nothing revalidated a stored posting. I sampled the newest 40 rows per site and 12.1% of what was being served was already dead, over half of it on two of the boards.",
      "",
      "So there is a liveness sweep now, and the design constraint is the same one as before: only positive evidence marks a row dead. A 404, an explicit gone-page, or a redirect that drops the posting id. A 403 or a timeout writes nothing at all.",
      "",
      "That restraint is not fussiness. 170 of 593 probes came back as refusals, and treating a refusal as an answer would have buried 168,238 live rows in a single pass. Nor can you outrun it: at concurrency 10, 126 of 200 probes came back unknown, so pushing harder converts live rows into unknowns faster rather than resolving more of them.",
      "",
      "## The same job, four times",
      "",
      "Cross-board duplicates are the most visible failure to a user and the least visible to a test. The identity key is accent-folded, punctuation-stripped, with company legal suffixes dropped, and it runs at write time and again on every read path, because write-time dedup can only ever see one batch and a duplicate that arrives tomorrow is still a duplicate.",
      "",
      "61,563 redundant rows have collapsed so far. The losing copies are recorded rather than deleted, which turns the whole problem into a feature: a row can say which other boards it also appeared on.",
      "",
      "## What I still cannot say",
      "",
      "The same rule has to point back at my own claims, and this is the part that stung. Not one of the three headline numbers on my own project page had been measured.",
      "",
      "- It used to say 2M postings, on no evidence at all. The index did pass 2M on the 2026-08-19 sweep, which is the least satisfying way to be right: a guess that lands is still a guess, and I only know it landed because I finally counted. The number stays on the page because it is now a census with a date on it, not because it was there first.",
      "- It used to say 60+ countries. That figure came from counting distinct search-location strings, so it was counting query regions and multi-counting any country I had searched under several city names. It has been pulled from every surface.",
      "- It used to say first results streamed in about 1.4 seconds. Nothing has timed that path since June, so it is withdrawn rather than repeated.",
      "",
      "And two live caveats I would rather write around than hide. Coverage is uneven: five sources account for 77.8% of the corpus, and on the last census six of the twenty disclosed boards had contributed no rows at all. The honest verb is that a search queries up to twenty boards, not that the index draws on twenty evenly. And liveness, for all the care above, had been probed on 0.32% of the corpus. The filter ships. The coverage does not exist yet.",
      "",
      "None of this makes the product look bigger. It is the only version of it I would put my name on, and it is the same instinct that made me re-measure my dissertation evaluation after submitting it and publish the correction. A number you cannot reproduce is not a result. It is a claim, and claims are cheap.",
    ].join("\n"),
  },
  {
    id: "seed-evaluating-rag-faithfulness-ragas",
    slug: "evaluating-rag-faithfulness-ragas",
    title: "What RAGAS taught me about evaluating RAG faithfulness",
    excerpt:
      "Building a RAG pipeline for UK financial regulation was the interesting part. Knowing whether its answers were actually grounded - not just fluent - is what RAGAS forced me to measure.",
    type: "blog",
    tags: ["RAG", "RAGAS", "Neo4j", "Sentence Transformers"],
    published: true,
    createdAt: "2026-07-01T08:15:00.000Z",
    updatedAt: "2026-07-01T08:15:00.000Z",
    content: [
      "FinLaw-UK was my MSc dissertation: a retrieval-augmented generation pipeline for UK financial regulation. The corpus is genuinely hard. The FCA Handbook alone runs to thousands of pages, cross-referenced with MiFID II, the PRA Rulebook, and a stack of binding technical standards. A naive LLM lookup answers confidently and wrongly in exactly the places where being wrong is most expensive.",
      "",
      "Building the retrieval and generation was the interesting engineering. The harder question came afterwards: how do I know an answer is actually grounded in the source, and not just fluent? That question is where RAGAS earned its place in the project.",
      "",
      "## Fluent and correct are not the same thing",
      "",
      "The first thing to accept is that surface metrics do not work here.",
      "",
      "BLEU and ROUGE reward text that reads like the reference. For regulatory text, that is close to worthless - a fluent paraphrase with one wrong citation is a liability, and it scores just as well as a correct answer. What I needed to measure was different: does the answer stay grounded in the context that was actually retrieved, and does it address the question that was actually asked? RAGAS scores exactly those two things, faithfulness and answer relevance, and both need an LLM judge reading the answer against the retrieved context rather than against a golden string.",
      "",
      "> A polished answer and a hallucinated one look identical until you check them against the source.",
      "",
      "## What faithfulness actually checks",
      "",
      "Faithfulness asks whether every claim in the answer is supported by the retrieved context. The idea is easier to see as a sketch than to describe:",
      "",
      "```python",
      "# Illustrative sketch of the idea - RAGAS uses an LLM judge, not this code",
      "claims = extract_claims(answer)",
      "supported = [c for c in claims if entailed_by(c, retrieved_context)]",
      "faithfulness = len(supported) / max(len(claims), 1)",
      "```",
      "",
      "A score near 1.0 means the answer invented nothing; a lower score means part of it came from the model's parameters rather than the documents in front of it. That framing quietly moves the burden onto retrieval - the generator can only be as faithful as the context it is handed.",
      "",
      "## The retrieval has to earn the score",
      "",
      "This is where plain vector search falls down. Dense retrieval finds passages that are semantically similar, but it misses the structure: a single rule is only meaningful alongside its parent chapter, the entities it obligates, and the rules it cross-references. Similarity does not recover that. The regulatory graph does.",
      "",
      "So ingestion runs two streams in parallel. Each section is chunked to its smallest semantic unit - usually a single rule - then embedded with Sentence Transformers into a vector index and, separately, parsed into a Neo4j knowledge graph that captures Rule-to-Chapter, Rule-to-Entity, and Rule-to-Cross-reference relationships.",
      "",
      "Generation itself is the easy part to describe: it runs locally on Mistral 7B-Instruct under citation-required prompting, where every claim has to reference a chunk ID and every chunk ID it cites has to exist in the retrieved set. That constraint is what makes a faithfulness score meaningful rather than aspirational. The interesting work happens before it, at query time:",
      "",
      "- Dense retrieval pulls the top-K candidate chunks.",
      "- A single-hop Cypher expansion in Neo4j adds adjacent rules, parent-chapter context, and cross-referenced sections.",
      "- The expanded set is re-ranked and trimmed to fit Mistral 7B-Instruct's context window.",
      "",
      "## The decisions that shaped it",
      "",
      "A few of them I would defend again:",
      "",
      "- Graph expansion over a better reranker - the failure mode was missing context, not mis-ranked context, and no reranker recovers a passage that was never retrieved.",
      "- Neo4j over a vector-only store like Pinecone or Qdrant - the cross-reference graph is the actual moat, and one Cypher hop expands it cheaply.",
      "- Mistral 7B over a frontier API - a small open-weight model running locally proved the retrieval gains held regardless of generator size, with no vendor dependency or data-egress problem on sensitive text.",
      "",
      "## What the numbers said, and what they didn't",
      "",
      "On a 110-item benchmark spanning seven regulatory domains, the pipeline reached 0.76 faithfulness and 0.74 answer relevance, with legal completeness at 0.68. Two other figures were in this paragraph until I re-measured the evaluation after submitting it: source accuracy and citation quality both came from a scorer that checked whether a string looked like a citation, not whether it was the right one. Both are withdrawn, and the correction is in the repo.",
      "",
      "The honest reading of 0.76 is that roughly three in four answers stay grounded and about a quarter drift. Those are not numbers to admire; they are the prompt-engineering targets for the next iteration. Answer relevance at 0.74 tracks faithfulness closely, which suggests the model stays on topic when it stays grounded - the two failure modes look related, not independent.",
      "",
      "## Where RAGAS stops helping",
      "",
      "RAGAS is good at catching faithfulness drift. It is not good at catching legal-specific failure modes. An answer can be perfectly grounded in a retrieved passage and still misapply it across jurisdictions, and faithfulness will score that highly. If I were taking this past the dissertation, the next moves are to extend the evaluation harness into a structured legal-reasoning benchmark, and to ship a confidence-aware interface that surfaces uncertainty when the graph expansion returns thin adjacency - so the person reading the answer knows whether it was reasoned from rich context or from sparse.",
    ].join("\n"),
  },
  {
    id: "seed-profiling-async-io-voice-agent-latency",
    slug: "profiling-async-io-voice-agent-latency",
    title: "Profiling async I/O: how we cut voice-agent latency 54%",
    excerpt:
      "A voice agent's quality is dominated by latency, and ours was clearing 2.4 seconds a turn. Getting it down to 1.1s was a profiling problem, not an architecture one.",
    type: "blog",
    tags: ["Python", "FastAPI", "AsyncIO", "PostgreSQL"],
    published: true,
    createdAt: "2026-06-16T09:30:00.000Z",
    updatedAt: "2026-06-16T09:30:00.000Z",
    content: [
      "A voice agent lives or dies on latency. At 2.4 seconds a turn it feels like a bad cell connection and the person on the other end starts talking over it; under 1.2 seconds it feels human enough that they stay on the call. Our outbound agent at Outlyst was clearing 2.4s on warm calls and getting worse under load - past roughly 200 concurrent sessions, response times spiked unpredictably and a fraction of calls dropped outright.",
      "",
      "The instinct in that situation is to reach for a bigger architecture. It was the wrong instinct.",
      "",
      "## The latency is in the middle, not the edges",
      "",
      "Retell AI handles the speech side - recognition and text-to-speech. Our backend only answers structured tool calls in between. So the round-trip a caller actually feels is dominated by what we do in those middle few hundred milliseconds, not by the model or the audio. The problem was not the design; it was measurement - find where the milliseconds go and stop losing them. The target was an average under 1.2s, held stable past 2,000 concurrent sessions, and no horizontal scaling, because throwing machines at it would have quietly killed the unit economics.",
      "",
      "## Profile the process that is actually under load",
      "",
      "I reached for py-spy rather than cProfile, and the reason matters. py-spy samples the running process from the outside, so I could attach it to the production backend under real traffic without restarting anything or distorting the numbers. cProfile's instrumentation would have moved exactly the timings I was trying to read.",
      "",
      "> A profiler that changes the timing it measures is measuring the wrong program.",
      "",
      "```bash",
      "# Illustrative: sample the live backend and render a flame graph",
      "py-spy record --pid $(pgrep -f 'uvicorn') --duration 60 --output profile.svg",
      "```",
      "",
      "The flame graph and the asyncio task traces surfaced two bottlenecks the request-rate dashboards had never shown:",
      "",
      "- A synchronous ORM call on every tool invocation, blocking the event loop.",
      "- A connection pool sized for the wrong shape of load - tuned for short HTTP request bursts, not long-lived websocket sessions.",
      "",
      "## Get the blocking call off the event loop",
      "",
      "One synchronous database call on the hot path does not just slow that one request - it stalls every coroutine sharing the loop. So I moved the hot path off SQLAlchemy and onto asyncpg.",
      "",
      "That was a deliberate trade. SQLAlchemy's async support is real, but its abstraction layers show up in a flame graph as frames you cannot cut. asyncpg is the actual driver: no ORM, no relationship modelling, no migrations at request time - none of which the inference backend needs. What it needs is fast reads and writes against a schema it already knows.",
      "",
      "## Size the pool for sessions, not requests",
      "",
      "The pool problem was subtler. A websocket call holds its session open for minutes, not milliseconds. A pool sized for HTTP request volume gave us a few dozen connections trying to serve thousands of concurrent, long-lived sessions, so callers queued on connection acquisition and the latency surfaced everywhere at once. Sizing the pool against the observed in-flight session distribution, rather than peak request rate, removed the contention without adding a single machine.",
      "",
      "## Stop doing independent work in sequence",
      "",
      "A single user turn often needed data from several places at once - CRM, calendar, contact enrichment. Those calls were independent but running one after another, so the turn paid for the sum of them. `asyncio.gather()` collapses them into one await:",
      "",
      "```python",
      "# Illustrative: independent tool calls in one turn, run concurrently",
      "crm, calendar, contact = await asyncio.gather(",
      "    fetch_crm(caller_id),",
      "    fetch_calendar(caller_id),",
      "    enrich_contact(caller_id),",
      ")",
      "```",
      "",
      "Now the turn is as slow as its slowest call, not the sum of all of them.",
      "",
      "There was one more change that was less about speed than waste: a lightweight gatekeeper-detection classifier that runs before the main inference loop. Cheap-and-fast beats expensive-and-smart - there is no reason to spend LLM tokens on a receptionist who is only going to transfer the call. Detected gatekeepers route to a callback scheduler instead of dead-ending, and each gated call saves roughly three to five minutes of call time.",
      "",
      "## What it added up to",
      "",
      "Mean call latency dropped from 2.4s to 1.1s - a 54% reduction - with no horizontal scaling and no change to the model. Across the contract the agent handled 2,100+ outbound calls at that latency. None of it came from a rewrite: the whole win was two profiling findings and a scheduling change.",
      "",
      "## Where the next milliseconds live",
      "",
      "The plumbing is mostly drained now. The next 200ms will not come from the surrounding I/O; it will have to come from the inference itself - speculative decoding, smaller models fine-tuned to the specific tool-call patterns we see, or moving the gatekeeper classifier onto a co-located CPU model so it costs almost nothing to run. That is a different kind of work, and it is where I would point next.",
    ].join("\n"),
  },
  {
    id: "seed-designing-legal-rag-benchmark",
    slug: "designing-legal-rag-benchmark",
    title: "Gold answers and required citations: designing a benchmark for legal RAG",
    excerpt:
      "The FinLaw-UK pipeline was scored against a benchmark I had to build first. Writing 110 legal QA items taught me more about RAG failure modes than building the pipeline did.",
    type: "case-study",
    tags: ["RAG", "Evaluation", "Benchmarks", "Neo4j"],
    published: true,
    createdAt: "2026-08-03T09:00:00.000Z",
    updatedAt: "2026-08-03T09:00:00.000Z",
    content: [
      "Every RAG write-up leads with the pipeline: the embedding model, the graph, the reranker. Almost none of them lead with the thing that decides whether any of it worked - the benchmark. For FinLaw-UK, my MSc dissertation on UK financial regulation QA, nobody hands you an eval set. I had to write one, and building it taught me more about where retrieval systems fail than building the retrieval did.",
      "",
      "## What one benchmark item has to carry",
      "",
      "A useful legal QA item is more than a question and an answer. Each item in the FinLaw-UK set carries four things: the question, a gold answer, the citations a correct answer must include, and the keywords the grader checks for. Here is a real one from the curated tier:",
      "",
      "- Question: \"Which FCA principle introduces the Consumer Duty?\"",
      "- Gold answer: the Consumer Duty is Principle 12, requiring firms to act to deliver good outcomes for retail customers.",
      "- Required citation: PRIN 12.",
      "- Graded keywords: Consumer Duty, good outcomes, Principle 12.",
      "",
      "The required-citation field is the one that earns its keep. The pipeline validates citations against a Neo4j knowledge graph of the regulatory corpus, so an answer citing a rule that does not exist in the graph is flagged as a potential hallucination. The benchmark mirrors that: an answer without PRIN 12 in it is wrong even if the prose is right, because in regulatory work an uncited claim is not an answer - it is a liability.",
      "",
      "## Composition matters more than size",
      "",
      "The full set is 110 items, and the split matters more than the count: 80 short-form questions, 20 document-level tasks, and 10 case-like scenarios, spanning domains from FSMA authorisation and conduct-of-business rules to payment services and complaints handling.",
      "",
      "Each tier probes a different failure mode. Short-form questions check retrieval precision: can the system find the one rule that answers a pointed question? Document tasks check synthesis: can it hold a whole chapter in view without dropping the cross-references? Scenarios check application: given a fact pattern, does it reach for the right regime at all? A benchmark that is all short-form questions will happily certify a system that falls over the moment a question spans two documents.",
      "",
      "## The aggregate score hid a broken scorer",
      "",
      "The headline numbers looked healthy: 0.82 source accuracy, 0.81 citation quality, 0.76 RAGAS faithfulness, 0.74 answer relevance. I submitted on those. Then I went back to reproduce them and found that two of the four were not measuring anything.",
      "",
      "The source-accuracy and citation-quality scorers were regex shape-checks. They tested whether a model output contained something shaped like a citation, not whether that citation was the right one, or real. Anything citation-shaped scored a flat 0.85. Once I looked at the distribution instead of the mean, 103 of the 110 rows carried that identical constant. The true rate, when every citation is resolved against the graph, was 3 in 110.",
      "",
      "> A mean can look reasonable while the distribution underneath it is a single repeated number. Plot the spread before you quote the average.",
      "",
      "Both figures are withdrawn. The repo now ships a measurement-integrity report saying which numbers reproduce and which do not, because a benchmark you release without that is worth less than no benchmark at all. The correction is also what motivated the parts of the system I am proudest of: the citation normaliser, the cross-encoder re-ranker, and the refusal gate that returns nothing rather than a citation it cannot verify.",
      "",
      "Refusing costs something, and the benchmark is what let me price it. Headline answer relevancy drops 23 points, because RAGAS scores a refusal as zero by construction. Exclude the 30 refusals and the mean is 0.658, against 0.641 for the non-refusing baseline. The baseline only scored higher by confabulating answers to questions the corpus cannot support, which is precisely the behaviour the gate exists to stop.",
      "",
      "## Where it actually failed",
      "",
      "The per-domain breakdown told a different story in one corner: consumer redress. DISP - the complaints-handling sourcebook - dragged legal completeness below 0.65. The reason is structural. DISP rules are fragmented into many small, heavily cross-referenced fragments, and the two-hop graph expansion that stitches context back together for the rest of the Handbook could not reassemble them. Rule-level chunking is the right default for most of the corpus; for DISP it shreds the very context the expansion is supposed to recover.",
      "",
      "That is a finding I only have because the benchmark was built to expose it: domain labels on every item meant the failure had an address, not just a lower average.",
      "",
      "## What I would build next",
      "",
      "Two things. Domain-aware chunk granularity for fragmented sourcebooks like DISP, so completeness recovers where the structure is hostile and deeper expansion alone will not do it. And a structured legal-reasoning benchmark beyond RAGAS, because faithfulness scoring cannot catch an answer that is perfectly grounded in a retrieved passage and still misapplies it across jurisdictions. The eval set is public in the repo alongside the pipeline and the integrity report; if you are building anything similar, steal the format - question, gold answer, required citations, graded keywords. The fourth column is the one you will thank yourself for, and it is the one that catches a scorer measuring shape instead of substance.",
    ].join("\n"),
  },
  {
    id: "seed-benchmarking-11-classifiers-diabetes-risk",
    slug: "benchmarking-11-classifiers-diabetes-risk",
    title: "11 classifiers, 253,680 records: what actually moved diabetes-risk accuracy",
    excerpt:
      "The model zoo was the easy part. The choices that moved accuracy were about class balance and what a person can self-report - not the estimator.",
    type: "blog",
    tags: ["Machine Learning", "scikit-learn", "Class Imbalance", "Interpretability"],
    published: true,
    createdAt: "2026-07-20T10:00:00.000Z",
    updatedAt: "2026-07-20T10:00:00.000Z",
    content: [
      "My BSc thesis at COMSATS asked a plain question: from a public health questionnaire, how well can you predict diabetes risk? The dataset was BRFSS 2015 - 253,680 CDC health records, 22 features - and the first thing it taught me was that the obvious way to answer is the wrong one. On an 86/14 imbalance, accuracy is not the question. Sensitivity and ROC-AUC are, because the expensive mistake here is the miss.",
      "",
      "## The imbalance decides before the model does",
      "",
      "BRFSS 2015 is 86/14 imbalanced: non-diabetic records outnumber diabetic ones six to one. That means a model that predicts \"not diabetic\" for everyone scores 86% accuracy while being clinically useless. Any accuracy figure on this dataset is meaningless until the balance is handled.",
      "",
      "We ran three balancing strategies head-to-head - Random Over-Sampling, SMOTE, and ADASYN, with the resampling confined to the training folds so the held-out split stayed untouched:",
      "",
      "```python",
      "# Illustrative: the head-to-head that decided the balancing strategy",
      "for sampler in (RandomOverSampler(), SMOTE(), ADASYN()):",
      "    X_bal, y_bal = sampler.fit_resample(X_train, y_train)",
      "    score = evaluate(model, X_bal, y_bal, X_test, y_test)",
      "```",
      "",
      "Plain Random Over-Sampling won, and the reason is worth remembering: SMOTE and ADASYN interpolate synthetic samples, which blurs categorical questionnaire features. There is no meaningful point halfway between \"has high blood pressure\" and \"does not\". Duplication preserved the feature distributions; interpolation smeared them.",
      "",
      "## Eleven models, one honest winner",
      "",
      "The benchmark spanned linear, instance-based, tree, boosting, and neural families - eleven classifiers under the same 80/20 split. The tree ensembles led, then the instance-based models, with the linear baseline last.",
      "",
      "That ordering was a measured finding, not an assumption. Running the full zoo is tedious, and it is also the only way the sentence \"Random Forest was best\" means anything.",
      "",
      "## Accuracy is not the metric that matters",
      "",
      "For a screening tool, the expensive mistake is the miss. Telling a healthy person to get a check-up costs an appointment; telling a diabetic person they are fine costs years of untreated progression. So the model was tuned to catch positives rather than to look tidy on a single headline metric - accepting more false alarms in exchange for missing fewer real cases. For screening, that is the right side of the trade to be on.",
      "",
      "## The constraint that shaped everything: no lab tests",
      "",
      "Every BRFSS feature is self-reportable - blood pressure history, BMI, activity, general health. That constraint became the product: a 19-question screen anyone can complete without a lab visit, served from a Flask API with a React front end, returning a risk classification and a future-risk probability. A model needing an HbA1c value would have been more precise and useless to the people the tool is for.",
      "",
      "## A prediction without a why is a black box",
      "",
      "Clinical adoption research is blunt about this: when clinicians cannot trace a prediction to features they recognise, they reject the tool - even when it outperforms their judgement. The thesis handled this with correlation-driven risk-factor analysis: general health was the strongest correlate at -0.41, then high blood pressure at +0.38, high cholesterol and BMI at +0.29 each, with prevalence climbing sharply from age 50 onward. Those are drivers a clinician already reasons with, which is the point: the explanation has to be in their vocabulary, not the model's.",
      "",
      "## What I would do differently",
      "",
      "Ship per-prediction attribution, not just population-level correlations - a risk score without \"why this score for this person\" is exactly the black box the thesis argued against. And before anything touches a real clinic: calibration and population-shift detection. 93% on one curated dataset does not transfer to a different hospital's intake unchecked, and Platt-scaled probabilities plus a shift detector are the difference between a paper result and a safe tool.",
    ].join("\n"),
  },
];
